### ISSUE TITLE
different image shape

### ISSUE THREAD

**Issue by luoww1992** [StefanoBerti/ISBFSAR#2]
when i change the test type with RealSense_pipeline by device name to test mp4 with opencv, the input frame size to h.estimate() is 640*480,
but  when i run hpe.py , it show me :

        Traceback (most recent call last):
          File "D:/ISBFSAR/modules/hpe/demo.py", line 259, in <module>
            res = h.estimate(img)
          File "D:/ISBFSAR/modules/hpe/demo.py", line 109, in estimate
            bbone_in = self.image_transformation([frame.astype(int), H.astype(np.float32)])
          File "D:\ISBFSAR\utils\tensorrt_runner.py", line 60, in __call__
            np.copyto(inp.host, elem)
          File "<__array_function__ internals>", line 180, in copyto
        ValueError: could not broadcast input array from shape (9,) into shape (45,)
why ?

**Comment by StefanoBerti** [comment]
Hi, did you rename hpe.py to demo.py?
Try to clone my latest push and run modules/hpe/hpe.py.
The system works both with rgb or skeleton input data and the input data type can be changed in utils/params/py.
Since this is a work in development some scripts may not work anymore, you may want to check main.py that is the most updated one.

**Comment by luoww1992** [comment]
> Hi, did you rename hpe.py to demo.py? Try to clone my latest push and run modules/hpe/hpe.py. The system works both with rgb or skeleton input data and the input data type can be changed in utils/params/py. Since this is a work in development some scripts may not work anymore, you may want to check main.py that is the most updated one.

yes， i copy the file hpe.py and rename it with demo.py to edit it , i am chenking the code, 
i find that maybe i need to change the batch_size=5 to batch_size=1, i thank it is the error place, now i am trying to run the setup again.

**Comment by StefanoBerti** [comment]
You are right, I have created 2 TRT engines: one with batch_size=1 and one with batch_size=5 for test time augmentation.
